[tool.poetry]
name = "pybricksdev"
version = "0.1.0"
description = "Pybricks developer tools"
authors = ["The Pybricks Authors <dev@pybricks.com>"]
maintainers = ["Laurens Valk <laurens@pybricks.com>", "David Lechner <david@pybricks.com>" ]
license = "MIT"
readme = "README.rst"
homepage = "https://pybricks.com"
repository = "https://github.com/pybricks/pybricksdev"

[tool.poetry.dependencies]
asyncssh = "*"
bleak = "*"
bricknil = { git = "https://github.com/pybricks/bricknil.git", branch = "firmware" }
curio = "*"
jupyter = "*"
mpy-cross = "==1.12"
nbstripout = "*"
python = "^3.8.2"
tqdm = "*"

[tool.poetry.dev-dependencies]
flake8 = "*"
pytest = "^5.2"
pybricks = { git = "https://github.com/pybricks/pybricks-api.git", branch = "master" }

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
