[tool.poetry]
name = "pybricksdev"
version = "0.1.0"
description = "Pybricks developer tools"
authors = ["The Pybricks Authors <dev@pybricks.com>"]
maintainers = ["Laurens Valk <laurens@pybricks.com>", "David Lechner <david@pybricks.com>" ]
license = "MIT"
readme = "README.rst"
homepage = "https://pybricks.com"
repository = "https://github.com/pybricks/pybricksdev"

[tool.poetry.scripts]
pybricksdev = 'pybricksdev.__main__:entry'

[tool.poetry.dependencies]
aioserial = { git = "https://github.com/pybricks/aioserial.git", branch = "master" }
argcomplete = "^1.11.1"
asyncssh = "^2.2.1"
bleak = { git = "https://github.com/pybricks/bleak.git", branch = "master" }
mpy-cross = "==1.12"
nbstripout = "^0.3.8"
python = "~3.8"
tqdm = "^4.46.1"
validators = "^0.15.0"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.3"
pytest = "^5.2"
pybricks = { git = "https://github.com/pybricks/pybricks-api.git", branch = "master" }
notebook = "^6.0.3"
ipykernel = "^5.3.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
