name: CI tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [ '3.8', '3.9', '3.10', '3.11' ]
    steps:
      - uses: actions/checkout@v3
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: poetry install
      - run: poetry run pytest
      - run: poetry run flake8 --show-source
        if: ${{ success() || failure() }}
      - run: poetry run black --check --diff .
        if: ${{ success() || failure() }}
      - run: poetry run make -C docs/ html
        if: ${{ success() || failure() }}
      - run: poetry run coverage run
      - run: |
          pipx install coveralls
          pipx inject coveralls coverage[toml]
      - run: coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
